# Use an official Node runtime as a parent image
FROM node:21

# Set the working directory
WORKDIR /app/frontend

# Copy the package.json and package-lock.json files and install the dependencies
COPY package*.json ./

# EXPOSE 3000
EXPOSE 5173
