version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend # mount the backend folder to the container

  frontend:
    build: 
      context: ./frontend
    command: "bash -c 'npm install && npm start'"
    ports:
      - "3000:3000"
      # - "5173:5173"
    # env_file:
    #   - .env
    volumes:
      - ./frontend:/app/frontend # mount the frontend folder to the container
      - ./frontend/node_modules:/app/frontend/node_modules # mount node_modules to the container
